name: deploy

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Linting (Pylint)
        run: pylint django_transformers_pipelines

      - name: Migrations
        run: |
          python boot_django.py makemigrations
          python boot_django.py migrate

      - name: Run Unit Tests
        run: |
          coverage run boot_django.py test
          coverage report
