name: deploy

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python Dependencies
        run: pip install -e .

      - name: Migrations
        run: |
          python boot_django.py makemigrations
          python boot_django.py migrate

      - name: Run Unit Tests
        run: python boot_django.py test
